### ISSUE TITLE
React Suite v4 feature tracking

### ISSUE THREAD

**Issue by simonguo** [rsuite/rsuite#453]
目前 React Suite v4 版本正在开发过程中，这个 Issue 会记录所有的新增功能以及一些破坏性的变更，同时也希望能够得到大家的修改意见。

预览地址 : https://next.rsuitejs.com

安装 :

```
npm install rsuite@next
```

### 4.0.0-alpha.0

- [x] **Feature**: 支持 `Placeholder` 组件 ([#418],[#420],[#423])
- [x] **Feature**: 支持 `List` 组件 ([#451])
- [x] **Feature**: `FormControl` 组件支持 `readOnly` 属性 ([#432])
- [x] **Feature**: `FormControl` 组件支持 `plaintext` 属性 ([#448],[#449])
- [x] **Feature**: `Whisper` 组件与所有的 `Picker` 组件支持 `preventOverfow` 属性，防止溢出。
- [x] **Breaking**: 调整 `Whisper` 组件与所有的 `Picker` 组件 `placement` 属性的值。([#443])
- [x] **Improve**: 调整色板算法，调整字体颜色对比度 ([#433])

### 4.0.0-alpha.1

- [x] **Feature**: 支持 `<Calendar>` 组件
- [x] **Feature**: 支持 `<Avatar>` 组件
- [x] **Feature**: 支持 `<Badge>` 组件
- [x] **Feature**: `Picker` 组件支持 `size` 属性

### 4.0.0-alpha.3

- [x] **Improve**: 从 Flow 迁移到 Typescript ([#531])
- [x] **Improve**: `<DatePicker>`和`<DateRangePicker>`组件支持 `showWeekNumbers` 属性，显示周数 ([#526] @viart)

### 4.0.0-alpha.6

- [x ] **Feature**: 支持 dark 主题
- [x ] **Feature**: `<Form>` 组件基于 Schema 支持异步校验
- [x ] **Feature**: `<TreePicker>` 与 `<CheckTreePicker>` 支持 `expandItemValues` 属性
- [x ] **Improve**: 重构 CSS, 优化文件体积

---

React Suite v4 is in the process of being developed. This issue will record all the new features and some breaking changes, and We hope to get everyone's comments.

Preview : https://next.rsuitejs.com

Install :

```
npm install rsuite@next
```

### 4.0.0-alpha.0

- [x] **Feature**: Add `<Placeholder>`. ([#418],[#420],[#423])
- [x] **Feature**: Add `<List>`. ([#451])
- [x] **Feature**: Support `readOnly` prop on `<FormControl>`. ([#432])
- [x] **Feature**: Support `plaintext` prop on `<FormControl>`. ([#448],[#449])
- [x] **Feature**: `<Whisper>` and all `Picker` components support the `preventOverfow` property to prevent overflow. ([#443])
- [x] **Breaking**: Adjust the value of `<Whisper>` with all `Picker` components `placement` properties.([#443])
- [x] **Improve**: Adjust swatch algorithm to adjust font color contrast ([#433])

### 4.0.0-alpha.1

- [x] **Feature**: Add `<Calendar>`
- [x] **Feature**: Add `<Avatar>`
- [x] **Feature**: Add `<Badge>`
- [x] **Feature**: Support `size` on all `Picker`

### 4.0.0-alpha.3

- [x] **Improve**: Migrate from Flow to Typescript ([#531])
- [x] **Improve**: Support `showWeekNumbers` on `<DatePicker>` and `<DateRangePicker>` ([#526] @viart)

### 4.0.0-alpha.6

- [x] **Feature**: Support dark theme
- [x ] **Feature**: Support for asynchronous validation in `<Form>`, based on Schema
- [x ] **Feature**: Support for `expandItemValues` on TreePicker and CheckTreePicker
- [x ] **Improve**: Refactor CSS to optimize file size

[#531]: https://github.com/rsuite/rsuite/pull/531
[#531]: https://github.com/rsuite/rsuite/pull/526
[#451]: https://github.com/rsuite/rsuite/pull/451
[#449]: https://github.com/rsuite/rsuite/pull/449
[#448]: https://github.com/rsuite/rsuite/pull/448
[#443]: https://github.com/rsuite/rsuite/pull/443
[#433]: https://github.com/rsuite/rsuite/pull/433
[#432]: https://github.com/rsuite/rsuite/pull/432
[#423]: https://github.com/rsuite/rsuite/pull/423
[#420]: https://github.com/rsuite/rsuite/pull/420
[#418]: https://github.com/rsuite/rsuite/pull/418

**Comment by kazarus** [comment]
types/TabelHeaderCell.d.ts   
Tabel是不是拼错了.
Tabel -> Table
